name: ğŸ¤“ Documentation ğŸ¤“

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron:  '23 0 * * *'

jobs:
  generate-docs:
    name: ğŸ”§ Generate and Publish Docs
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write

    steps:
      - name: ğŸ  Checkout repository
        uses: actions/checkout@v3
      - name: â›ï¸ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: "npm install"
        run: npm install
      - name: "Create docs folder"
        run: mkdir docs
      - name: "Install xdot"
        run: sudo apt-get update; sudo apt-get install xdot
      - name: "Generate Documentation"
        run: npm run docs
      - name: ğŸ¥¸ Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          check-latest: true
      - name: ğŸ”¥ Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: ğŸ¦¾ Build Swagger UI
        run: mvn clean compile -Pswagger-ui
      - name: ğŸš€ deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
